# permissions for end users to edit podinfoconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podinfoconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: podinfoconfig-editor-role
  namespace: pw5-yournamehere-operator #to set in variable
rules:
- apiGroups:
  - tuto.config
  resources:
  - podinfoconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tuto.config
  resources:
  - podinfoconfigs/status
  verbs:
  - get
