# permissions for end users to view podinfoconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podinfoconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: podinfoconfig-viewer-role
rules:
- apiGroups:
  - tuto.config
  resources:
  - podinfoconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tuto.config
  resources:
  - podinfoconfigs/status
  verbs:
  - get
