---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tuto.config
  resources:
  - podinfoconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tuto.config
  resources:
  - podinfoconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - tuto.config
  resources:
  - podinfoconfigs/status
  verbs:
  - get
  - patch
  - update
