apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: {{ .Values.serviceaccount | default "controller-manager-podinfo-operator" }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: {{ .Values.serviceaccount | default "controller-manager-podinfo-operator" }}
  namespace: {{ .Values.namespace | default "default" }}
