name: Deploy podinfo operator to GHCR

env:
  DOTNET_VERSION: '6.2.1'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        permissions:
          packages: write
        defaults:
          run:
            working-directory: './docker-source'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/francoisdeturenne/podinfo-op-debug:$DOTNET_VERSION
              docker push ghcr.io/francoisdeturenne/podinfo-op-debug:$DOTNET_VERSION